import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GrainEffect from "./components/visualEffects/grain-effect";
import Cursor from "./components/cursor/cursor";
import { FloatingNavDemo } from "./components/nav";
import scrollTop from "./components/scrollToTop/scrollToTop";
import { cn } from "@/utils/cn";
import ScrollToTop from "react-scroll-to-top";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {/* <GrainEffect/> */}
        <Cursor/>
        <FloatingNavDemo />
        {children}</body>
    </html>
  );
}
